# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a2c72430726797ca1a12d76edf820ecf98c2378822dad2531b16163bf25948d9339292ed263aa0c1959d7b9bc1fe76e9855c7a4c0a2d057515e292540586c1d

test:
  secret_key_base: ce5d59a0c8e4091bde9bfcddd89f2d2d37ae3003be5f22698d812fe12089eb46ba0a4a97fd7e7efcee9a7fdd1deece023035c126efc1e4162a74371a6135cc02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
